services:
  nginx:
    build: ./requirements/nginx
    image:  nginx:inception
    pull_policy: build
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      - inception
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:?Set DOMAIN_NAME in .env}

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    pull_policy: build
    restart: unless-stopped
    networks:
      - inception
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:?Set MYSQL_DATABASE in .env}
      MYSQL_USER: ${MYSQL_USER:? Set MYSQL_USER in .env}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?Set MYSQL_PASSWORD in .env}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?Set MYSQL_ROOT_PASSWORD in .env}
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/eeravci/data/mariadb"
   